// syntax.ts — the parser's verb syntaxes and action tables
//
// Translated from the original ZIL source of Leather Goddesses of Phobos
// (c) 1986 Infocom, Inc. by tools/zil2ts. Structure, names and logic follow
// the original routine for routine.

import {
  actionTable, prepositionTable, syntaxTable, verbsTable,
} from "../engine/syntax.ts";
import {
  word,
} from "../engine/vocab.ts";
import {
  idrop, preBoard, preFuck, preGive, preListen, preLook, prePour, prePut, preRake, preSmell, preSpeak,
  preTake, preTouch, vAlarm, vAnswer, vAnswerKludge, vApplaud, vApply, vAskAbout, vAskFor,
  vAskNoOneFor, vBarterFor, vBarterWith, vBend, vBite, vBlow, vBoard, vBoardDir, vBrief, vBurn, vBuy,
  vBuyWith, vCall, vCastOff, vCatch, vChastise, vCheer, vClean, vClick, vClimb, vClimbDown, vClimbOn,
  vClimbOver, vClimbUp, vClose, vCome, vCopulate, vCount, vCrawlUnder, vCross, vCut, vDecode, vDeflate,
  vDiagnose, vDig, vDisembark, vDollarCommand, vDollarRandom, vDollarRecord, vDollarUnrecord,
  vDollarVerify, vDress, vDrink, vDrinkFrom, vDrop, vEat, vEmpty, vEmptyFrom, vEnter, vExamine, vExit,
  vFeed, vFill, vFind, vFlush, vFollow, vFuck, vGetDressed, vGetDrunk, vGetUndressed, vGiddyap, vGive,
  vGiveUp, vHello, vHelp, vHide, vHiss, vIn, vInflate, vInhale, vInventory, vKick, vKill, vKiss,
  vKissOn, vKneel, vKnock, vKweepa, vLand, vLaugh, vLaunch, vLeap, vLeapOff, vLeave, vLewd, vLick,
  vLieDown, vLimber, vListen, vLock, vLook, vLookBehind, vLookDown, vLookInside, vLookOver, vLookUnder,
  vLookUp, vLove, vLower, vMake, vMakeLove, vMakeOut, vMakeWith, vMarry, vMasturbate, vMeasure, vMoan,
  vMove, vMung, vNo, vOff, vOn, vOpen, vPass, vPay, vPee, vPeeIn, vPhone, vPick, vPickUp, vPin, vPoint,
  vPour, vPush, vPushDir, vPushOff, vPut, vPutAgainst, vPutBehind, vPutNear, vPutOn, vPutThrough,
  vPutTo, vPutUnder, vQuit, vRaise, vRake, vRape, vReachIn, vRead, vRelieve, vRemove, vRestart,
  vRestore, vReturn, vRip, vRoll, vRub, vSave, vSaveSomething, vSay, vScat, vScore, vScript, vSearch,
  vSet, vSgive, vShake, vShakeWith, vShit, vShow, vShutUp, vSigh, vSink, vSit, vSkip, vSleep, vSmell,
  vSputOn, vSrub, vSshow, vStain, vStand, vStandOn, vStatus, vStell, vSthrow, vSuck, vSuckle,
  vSuggestive, vSuperBrief, vSwim, vSwing, vSwrap, vTake, vTakeALeak, vTakeAShit, vTakeOff, vTakeWith,
  vTame, vTaste, vTell, vTellAbout, vThank, vThrow, vThrowTo, vThrowUp, vTie, vTieTogether, vTouch,
  vUncover, vUndress, vUnlock, vUnroll, vUnscript, vUntie, vUse, vUseQuotes, vVerbose, vVersion,
  vVomit, vWait, vWaitFor, vWalk, vWalkAround, vWalkTo, vWear, vWhat, vWhere, vWhip, vWrap, vYell,
  vYes,
} from "./verbs.ts";
import {
  ACT, ACTORBIT, BURNBIT, CONTBIT, DOORBIT, LIGHTBIT, ONBIT, PR, READBIT, RLANDBIT, SC, SH, SHAVE, SIR,
  SMANY, SOG, STAKE, TAKEBIT, V, VEHBIT, WEARBIT, WORNBIT,
} from "./world.ts";

/**
 * Each verb's syntaxes, in the order the original compiler stored them
 * (reverse of their order in SYNTAX.ZIL). The parser uses the last match.
 */
export const VERBS = verbsTable([
  [ACT.VERBOSE, syntaxTable("VERBOSE", [
    { objects: 0, action: V.VERBOSE },
  ])],
  [ACT.BRIEF, syntaxTable("BRIEF", [
    { objects: 0, action: V.BRIEF },
  ])],
  [ACT.SUPER, syntaxTable("SUPER", [
    { objects: 0, action: V.SUPER_BRIEF },
  ])],
  [ACT.TAME, syntaxTable("TAME", [
    { objects: 0, action: V.TAME },
  ])],
  [ACT.SUGGESTIVE, syntaxTable("SUGGESTIVE", [
    { objects: 0, action: V.SUGGESTIVE },
  ])],
  [ACT.LEWD, syntaxTable("LEWD", [
    { objects: 0, action: V.LEWD },
  ])],
  [ACT.DIAGNOSE, syntaxTable("DIAGNOSE", [
    { objects: 0, action: V.DIAGNOSE },
  ])],
  [ACT.INVENT, syntaxTable("INVENT", [
    { objects: 0, action: V.INVENTORY },
  ])],
  [ACT.QUIT, syntaxTable("QUIT", [
    { objects: 0, action: V.QUIT },
  ])],
  [ACT.RESTAR, syntaxTable("RESTAR", [
    { objects: 0, action: V.RESTART },
  ])],
  [ACT.RESTOR, syntaxTable("RESTOR", [
    { objects: 0, action: V.RESTORE },
  ])],
  [ACT.SAVE, syntaxTable("SAVE", [
    { objects: 1, action: V.SAVE_SOMETHING },
    { objects: 0, action: V.SAVE },
  ])],
  [ACT.STATUS, syntaxTable("STATUS", [
    { objects: 0, action: V.STATUS },
  ])],
  [ACT.SCRIPT, syntaxTable("SCRIPT", [
    { objects: 0, action: V.SCRIPT },
  ])],
  [ACT.UNSCRIPT, syntaxTable("UNSCRIPT", [
    { objects: 0, action: V.UNSCRIPT },
  ])],
  [ACT.VERSION, syntaxTable("VERSION", [
    { objects: 0, action: V.VERSION },
  ])],
  [ACT["#RANDOM"], syntaxTable("#RANDOM", [
    { objects: 1, action: V.$RANDOM },
  ])],
  [ACT["#COMMAND"], syntaxTable("#COMMAND", [
    { objects: 0, action: V.$COMMAND },
  ])],
  [ACT["#RECORD"], syntaxTable("#RECORD", [
    { objects: 0, action: V.$RECORD },
  ])],
  [ACT["#UNRECORD"], syntaxTable("#UNRECORD", [
    { objects: 0, action: V.$UNRECORD },
  ])],
  [ACT.$VERIFY, syntaxTable("$VERIFY", [
    { objects: 1, action: V.$VERIFY },
    { objects: 0, action: V.$VERIFY },
  ])],
  [ACT.ANSWER, syntaxTable("ANSWER", [
    { objects: 1, action: V.USE_QUOTES },
    { objects: 0, action: V.ANSWER },
  ])],
  [ACT.APPLAUD, syntaxTable("APPLAUD", [
    { objects: 1, action: V.APPLAUD },
    { objects: 0, action: V.APPLAUD },
  ])],
  [ACT.APPLY, syntaxTable("APPLY", [
    { objects: 2, prep2: PR.TO, loc1: SH | SMANY, action: V.PUT_ON },
    { objects: 1, loc1: SH | STAKE, action: V.APPLY },
  ])],
  [ACT.APPROA, syntaxTable("APPROA", [
    { objects: 1, action: V.WALK_TO },
  ])],
  [ACT.ASK, syntaxTable("ASK", [
    { objects: 1, prep1: PR.FOR, action: V.ASK_NO_ONE_FOR },
    { objects: 2, prep2: PR.FOR, find1: ACTORBIT, action: V.ASK_FOR },
    { objects: 2, prep2: PR.ON, find1: ACTORBIT, action: V.ASK_ABOUT },
    { objects: 2, prep2: PR.ABOUT, find1: ACTORBIT, action: V.ASK_ABOUT },
  ])],
  [ACT.ATTACK, syntaxTable("ATTACK", [
    { objects: 2, prep2: PR.WITH, find1: ACTORBIT, loc1: SOG | SIR, loc2: SH | SC | SHAVE, action: V.KILL },
    { objects: 1, find1: ACTORBIT, loc1: SOG | SIR, action: V.KILL },
  ])],
  [ACT.BARTER, syntaxTable("BARTER", [
    { objects: 2, prep2: PR.FOR, loc1: SH | SC | SHAVE, action: V.BARTER_FOR },
    { objects: 1, prep1: PR.FOR, action: V.BARTER_FOR },
    { objects: 1, prep1: PR.WITH, find1: ACTORBIT, action: V.BARTER_WITH },
  ])],
  [ACT.BEND, syntaxTable("BEND", [
    { objects: 1, action: V.BEND },
  ])],
  [ACT.BITE, syntaxTable("BITE", [
    { objects: 1, action: V.BITE },
  ])],
  [ACT.BLOW, syntaxTable("BLOW", [
    { objects: 1, prep1: PR.OUT, find1: ONBIT, action: V.OFF },
    { objects: 1, prep1: PR.UP, action: V.INFLATE },
    { objects: 1, action: V.BLOW },
  ])],
  [ACT.BOARD, syntaxTable("BOARD", [
    { objects: 2, action: V.BOARD_DIR },
    { objects: 1, find1: VEHBIT, loc1: SOG | SIR, action: V.BOARD },
  ])],
  [ACT.BREATHE, syntaxTable("BREATHE", [
    { objects: 1, prep1: PR.HARD, find1: RLANDBIT, action: V.INHALE },
    { objects: 0, action: V.INHALE },
  ])],
  [ACT.BURN, syntaxTable("BURN", [
    { objects: 2, prep1: PR.UP, prep2: PR.WITH, find1: BURNBIT, loc2: SHAVE, action: V.BURN },
    { objects: 2, prep2: PR.WITH, find1: BURNBIT, loc2: SHAVE, action: V.BURN },
    { objects: 1, prep1: PR.UP, find1: BURNBIT, action: V.BURN },
    { objects: 1, find1: BURNBIT, action: V.BURN },
  ])],
  [ACT.BUY, syntaxTable("BUY", [
    { objects: 2, prep2: PR.WITH, action: V.BUY_WITH },
    { objects: 2, prep2: PR.FROM, action: V.BUY },
    { objects: 1, action: V.BUY },
  ])],
  [ACT.CALL, syntaxTable("CALL", [
    { objects: 1, prep1: PR.TO, action: V.CALL },
    { objects: 1, prep1: PR.OUT, action: V.CALL },
    { objects: 1, action: V.CALL },
  ])],
  [ACT.CAST, syntaxTable("CAST", [
    { objects: 1, prep1: PR.OFF, find1: RLANDBIT, action: V.CAST_OFF },
  ])],
  [ACT.CATCH, syntaxTable("CATCH", [
    { objects: 2, prep2: PR.WITH, loc1: SOG | SIR, action: V.CATCH },
    { objects: 2, prep2: PR.IN, loc1: SOG | SIR, action: V.CATCH },
    { objects: 1, loc1: SOG | SIR, action: V.CATCH },
  ])],
  [ACT.CHEER, syntaxTable("CHEER", [
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.CHEER },
    { objects: 1, find1: ACTORBIT, action: V.CHEER },
  ])],
  [ACT.CIRCLE, syntaxTable("CIRCLE", [
    { objects: 1, action: V.WALK_AROUND },
  ])],
  [ACT.CLICK, syntaxTable("CLICK", [
    { objects: 1, action: V.CLICK },
  ])],
  [ACT.CLIMB, syntaxTable("CLIMB", [
    { objects: 1, prep1: PR.UNDER, action: V.CRAWL_UNDER },
    { objects: 1, prep1: PR.THROUGH, action: V.ENTER },
    { objects: 1, prep1: PR.IN, find1: VEHBIT, loc1: SOG | SIR, action: V.BOARD },
    { objects: 1, prep1: PR.OVER, loc1: SOG | SIR, action: V.CLIMB_OVER },
    { objects: 1, prep1: PR.OFF, find1: VEHBIT, loc1: SOG | SIR, action: V.DISEMBARK },
    { objects: 1, prep1: PR.OUT, find1: VEHBIT, loc1: SOG | SIR, action: V.DISEMBARK },
    { objects: 1, prep1: PR.DOWN, find1: RLANDBIT, loc1: SOG | SIR, action: V.CLIMB_DOWN },
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, loc1: SOG | SIR, action: V.CLIMB_UP },
    { objects: 1, prep1: PR.ON, find1: VEHBIT, loc1: SOG | SIR, action: V.CLIMB_ON },
    { objects: 1, loc1: SOG | SIR, action: V.CLIMB },
  ])],
  [ACT.CLOSE, syntaxTable("CLOSE", [
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.SHUT_UP },
    { objects: 1, prep1: PR.OFF, find1: LIGHTBIT, loc1: SH | SC | SOG | SIR | STAKE, action: V.OFF },
    { objects: 1, find1: DOORBIT, loc1: SH | SC | SOG | SIR, action: V.CLOSE },
  ])],
  [ACT.COME, syntaxTable("COME", [
    { objects: 1, prep1: PR.WITH, action: V.FOLLOW },
    { objects: 0, action: V.COME },
  ])],
  [ACT.COPULATE, syntaxTable("COPULATE", [
    { objects: 0, action: V.COPULATE },
  ])],
  [ACT.COVER, syntaxTable("COVER", [
    { objects: 2, prep2: PR.WITH, loc2: SH | SMANY, action: V.SPUT_ON },
  ])],
  [ACT.COUNT, syntaxTable("COUNT", [
    { objects: 1, action: V.COUNT },
  ])],
  [ACT.CROSS, syntaxTable("CROSS", [
    { objects: 1, action: V.CROSS },
  ])],
  [ACT.DECODE, syntaxTable("DECODE", [
    { objects: 1, action: V.DECODE },
  ])],
  [ACT.DEFLATE, syntaxTable("DEFLATE", [
    { objects: 2, prep2: PR.WITH, loc2: SHAVE, action: V.DEFLATE },
    { objects: 1, action: V.DEFLATE },
  ])],
  [ACT.DEMOLI, syntaxTable("DEMOLI", [
    { objects: 1, prep1: PR.DOWN, action: V.KILL },
    { objects: 1, prep1: PR.OUT, find1: RLANDBIT, action: V.MUNG },
    { objects: 2, prep2: PR.WITH, loc2: SH | SC | STAKE, action: V.MUNG },
    { objects: 1, loc1: SOG | SIR, action: V.MUNG },
  ])],
  [ACT.DESCEN, syntaxTable("DESCEN", [
    { objects: 1, loc1: SOG | SIR, action: V.CLIMB_DOWN },
  ])],
  [ACT.DIG, syntaxTable("DIG", [
    { objects: 1, prep1: PR.THROUGH, action: V.DIG },
    { objects: 1, prep1: PR.IN, action: V.DIG },
  ])],
  [ACT.DISEMBARK, syntaxTable("DISEMBARK", [
    { objects: 1, loc1: SOG | SIR, action: V.DISEMBARK },
    { objects: 0, action: V.DISEMBARK },
  ])],
  [ACT.DRESS, syntaxTable("DRESS", [
    { objects: 1, action: V.DRESS },
    { objects: 0, action: V.DRESS },
  ])],
  [ACT.DRINK, syntaxTable("DRINK", [
    { objects: 1, prep1: PR.FROM, loc1: SH | SC, action: V.DRINK_FROM },
    { objects: 1, loc1: SH | SC | SOG | SIR, action: V.DRINK },
  ])],
  [ACT.DROP, syntaxTable("DROP", [
    { objects: 2, prep2: PR.AT, loc1: SH | SC, action: V.PUT_NEAR },
    { objects: 2, prep2: PR.BEFORE, loc1: SH | SC, action: V.PUT_NEAR },
    { objects: 2, prep2: PR.THROUGH, loc1: SH | SMANY, action: V.PUT_THROUGH },
    { objects: 2, prep2: PR.OUT, loc1: SH | SMANY, action: V.PUT_THROUGH },
    { objects: 2, prep2: PR.ON, loc1: SH | SMANY, action: V.PUT_ON },
    { objects: 2, prep2: PR.IN, loc1: SH | SMANY, action: V.PUT },
    { objects: 2, prep2: PR.DOWN, loc1: SH | SMANY, action: V.PUT },
    { objects: 1, loc1: SH | SMANY | SHAVE, action: V.DROP },
  ])],
  [ACT.EAT, syntaxTable("EAT", [
    { objects: 1, loc1: SH | SC | SOG | SIR, action: V.EAT },
  ])],
  [ACT.EMPTY, syntaxTable("EMPTY", [
    { objects: 2, prep2: PR.THROUGH, loc1: SHAVE | STAKE, action: V.EMPTY_FROM },
    { objects: 2, prep2: PR.OUT, loc1: SMANY, loc2: SHAVE | STAKE, action: V.EMPTY_FROM },
    { objects: 2, prep2: PR.FROM, loc1: SMANY, loc2: SHAVE | STAKE, action: V.EMPTY_FROM },
    { objects: 2, prep2: PR.TO, loc1: SHAVE | STAKE, action: V.EMPTY },
    { objects: 2, prep2: PR.IN, loc1: SHAVE | STAKE, action: V.EMPTY },
    { objects: 2, prep2: PR.ON, loc1: SHAVE | STAKE, action: V.EMPTY },
    { objects: 2, prep2: PR.OVER, loc1: SHAVE | STAKE, action: V.EMPTY },
    { objects: 1, prep1: PR.OUT, loc1: SHAVE | STAKE, action: V.EMPTY },
    { objects: 1, loc1: SHAVE | STAKE, action: V.EMPTY },
  ])],
  [ACT.ENTER, syntaxTable("ENTER", [
    { objects: 1, action: V.ENTER },
    { objects: 0, action: V.IN },
  ])],
  [ACT.EXAMINE, syntaxTable("EXAMINE", [
    { objects: 1, loc1: SH | SC | SOG | SIR, action: V.EXAMINE },
  ])],
  [ACT.EXIT, syntaxTable("EXIT", [
    { objects: 1, action: V.EXIT },
    { objects: 0, action: V.EXIT },
  ])],
  [ACT.EXTINGUISH, syntaxTable("EXTINGUISH", [
    { objects: 1, find1: ONBIT, action: V.OFF },
  ])],
  [ACT.FEED, syntaxTable("FEED", [
    { objects: 2, find1: ACTORBIT, loc1: SOG, loc2: SMANY | SH | SHAVE, action: V.SGIVE },
    { objects: 2, prep2: PR.TO, find2: ACTORBIT, loc1: SMANY | SH | SHAVE, loc2: SOG, action: V.GIVE },
    { objects: 1, find1: ACTORBIT, action: V.FEED },
  ])],
  [ACT.FILL, syntaxTable("FILL", [
    { objects: 2, prep2: PR.WITH, find1: CONTBIT, loc1: SH | SC | SHAVE, action: V.FILL },
    { objects: 1, find1: CONTBIT, loc1: SH | SC | SHAVE, action: V.FILL },
  ])],
  [ACT.FIND, syntaxTable("FIND", [
    { objects: 1, action: V.FIND },
  ])],
  [ACT.FLUSH, syntaxTable("FLUSH", [
    { objects: 1, action: V.FLUSH },
  ])],
  [ACT.FOLLOW, syntaxTable("FOLLOW", [
    { objects: 1, action: V.FOLLOW },
  ])],
  [ACT.FUCK, syntaxTable("FUCK", [
    { objects: 1, find1: ACTORBIT, action: V.FUCK },
  ])],
  [ACT.GIDDYAP, syntaxTable("GIDDYAP", [
    { objects: 0, action: V.GIDDYAP },
  ])],
  [ACT.GO, syntaxTable("GO", [
    { objects: 1, prep1: PR.WITH, action: V.FOLLOW },
    { objects: 1, prep1: PR.AWAY, find1: RLANDBIT, action: V.LEAVE },
    { objects: 1, prep1: PR.TO, action: V.WALK_TO },
    { objects: 1, prep1: PR.DOWN, loc1: SOG | SIR, action: V.CLIMB_DOWN },
    { objects: 1, prep1: PR.UP, loc1: SOG | SIR, action: V.CLIMB_UP },
    { objects: 1, prep1: PR.BEHIND, action: V.HIDE },
    { objects: 1, prep1: PR.UNDER, action: V.CRAWL_UNDER },
    { objects: 1, prep1: PR.AROUND, find1: RLANDBIT, action: V.WALK_AROUND },
    { objects: 1, prep1: PR.THROUGH, action: V.ENTER },
    { objects: 1, prep1: PR.OUT, action: V.ENTER },
    { objects: 1, prep1: PR.IN, action: V.ENTER },
    { objects: 1, action: V.WALK },
  ])],
  [ACT.HAND, syntaxTable("HAND", [
    { objects: 2, prep2: PR.BACK, find2: ACTORBIT, loc1: SMANY | SH | SHAVE, loc2: SOG, action: V.GIVE },
    { objects: 1, prep1: PR.BACK, loc1: SH | SC | SHAVE, action: V.RETURN },
    { objects: 2, prep2: PR.FOR, loc1: SH | SC | SHAVE, action: V.BARTER_FOR },
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.GIVE_UP },
    { objects: 2, find1: ACTORBIT, loc1: SOG, loc2: SMANY | SH | SHAVE, action: V.SGIVE },
    { objects: 2, prep2: PR.TO, find2: ACTORBIT, loc1: SMANY | SH | SHAVE, loc2: SOG, action: V.GIVE },
  ])],
  [ACT.HEAR, syntaxTable("HEAR", [
    { objects: 1, action: V.LISTEN },
  ])],
  [ACT.HELLO, syntaxTable("HELLO", [
    { objects: 1, action: V.HELLO },
    { objects: 0, action: V.HELLO },
  ])],
  [ACT.HELP, syntaxTable("HELP", [
    { objects: 1, action: V.SAVE_SOMETHING },
    { objects: 0, action: V.HELP },
  ])],
  [ACT.HIDE, syntaxTable("HIDE", [
    { objects: 1, prep1: PR.BEHIND, action: V.HIDE },
    { objects: 1, prep1: PR.UNDER, action: V.HIDE },
    { objects: 0, action: V.HIDE },
  ])],
  [ACT.HISS, syntaxTable("HISS", [
    { objects: 1, prep1: PR.AT, action: V.HISS },
    { objects: 0, action: V.HISS },
  ])],
  [ACT.INFLATE, syntaxTable("INFLATE", [
    { objects: 1, action: V.INFLATE },
  ])],
  [ACT.JERK, syntaxTable("JERK", [
    { objects: 2, prep2: PR.WITH, loc2: SHAVE, action: V.WHIP },
    { objects: 1, prep1: PR.OFF, find1: RLANDBIT, action: V.MASTURBATE },
  ])],
  [ACT.JUMP, syntaxTable("JUMP", [
    { objects: 1, prep1: PR.TO, action: V.LEAP },
    { objects: 1, prep1: PR.DOWN, find1: RLANDBIT, action: V.LEAP },
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.LEAP },
    { objects: 1, prep1: PR.THROUGH, action: V.ENTER },
    { objects: 1, prep1: PR.OUT, action: V.LEAP_OFF },
    { objects: 1, prep1: PR.ACROSS, action: V.LEAP },
    { objects: 1, prep1: PR.ON, action: V.STAND_ON },
    { objects: 1, prep1: PR.OFF, action: V.LEAP_OFF },
    { objects: 1, prep1: PR.FROM, action: V.LEAP_OFF },
    { objects: 1, prep1: PR.IN, action: V.ENTER },
    { objects: 1, prep1: PR.ACROSS, action: V.LEAP },
    { objects: 1, prep1: PR.OVER, action: V.LEAP },
    { objects: 0, action: V.LEAP },
  ])],
  [ACT.KICK, syntaxTable("KICK", [
    { objects: 1, action: V.KICK },
  ])],
  [ACT.KISS, syntaxTable("KISS", [
    { objects: 2, prep2: PR.ON, find1: ACTORBIT, action: V.KISS_ON },
    { objects: 1, find1: ACTORBIT, loc1: SOG | SIR, action: V.KISS },
  ])],
  [ACT.KNEEL, syntaxTable("KNEEL", [
    { objects: 1, prep1: PR.FOR, find1: ACTORBIT, action: V.KNEEL },
    { objects: 1, prep1: PR.BEFORE, find1: ACTORBIT, action: V.KNEEL },
    { objects: 1, prep1: PR.TO, find1: ACTORBIT, action: V.KNEEL },
  ])],
  [ACT.KNOCK, syntaxTable("KNOCK", [
    { objects: 1, prep1: PR.DOWN, find1: ACTORBIT, loc1: SOG | SIR, action: V.KILL },
    { objects: 1, prep1: PR.AT, find1: DOORBIT, action: V.KNOCK },
    { objects: 1, prep1: PR.ON, find1: DOORBIT, action: V.KNOCK },
  ])],
  [ACT.KWEEPA, syntaxTable("KWEEPA", [
    { objects: 0, action: V.KWEEPA },
  ])],
  [ACT.LAND, syntaxTable("LAND", [
    { objects: 1, find1: VEHBIT, action: V.LAND },
    { objects: 0, action: V.LAND },
  ])],
  [ACT.LAUGH, syntaxTable("LAUGH", [
    { objects: 1, prep1: PR.AT, action: V.LAUGH },
    { objects: 0, action: V.LAUGH },
  ])],
  [ACT.LAUNCH, syntaxTable("LAUNCH", [
    { objects: 1, action: V.LAUNCH },
  ])],
  [ACT.LEAN, syntaxTable("LEAN", [
    { objects: 2, prep2: PR.AGAINST, loc1: SHAVE, action: V.PUT_AGAINST },
    { objects: 2, prep2: PR.ON, loc1: SHAVE, action: V.PUT_AGAINST },
  ])],
  [ACT.LEAVE, syntaxTable("LEAVE", [
    { objects: 2, prep2: PR.AT, loc1: SH | SC, action: V.PUT_NEAR },
    { objects: 2, prep2: PR.BEFORE, loc1: SH | SC, action: V.PUT_NEAR },
    { objects: 2, prep2: PR.ON, loc1: SH | SMANY, action: V.PUT_ON },
    { objects: 2, prep2: PR.IN, loc1: SH | SMANY, action: V.PUT },
    { objects: 1, action: V.LEAVE },
    { objects: 0, action: V.LEAVE },
  ])],
  [ACT.LET, syntaxTable("LET", [
    { objects: 1, prep1: PR.GO, loc1: SH | SMANY | SHAVE, action: V.DROP },
  ])],
  [ACT.LICK, syntaxTable("LICK", [
    { objects: 1, action: V.LICK },
  ])],
  [ACT.LIE, syntaxTable("LIE", [
    { objects: 1, prep1: PR.DOWN, find1: RLANDBIT, action: V.LIE_DOWN },
    { objects: 1, prep1: PR.IN, find1: VEHBIT, action: V.LIE_DOWN },
    { objects: 1, prep1: PR.ON, find1: VEHBIT, action: V.LIE_DOWN },
  ])],
  [ACT.LIGHT, syntaxTable("LIGHT", [
    { objects: 1, find1: LIGHTBIT, loc1: SH | SC | SOG | SIR, action: V.ON },
  ])],
  [ACT.LIMBER, syntaxTable("LIMBER", [
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.LIMBER },
    { objects: 0, action: V.LIMBER },
  ])],
  [ACT.LISTEN, syntaxTable("LISTEN", [
    { objects: 1, prep1: PR.TO, action: V.LISTEN },
    { objects: 0, action: V.LISTEN },
  ])],
  [ACT.LOCK, syntaxTable("LOCK", [
    { objects: 2, prep2: PR.WITH, loc1: SOG | SIR, action: V.LOCK },
    { objects: 1, action: V.LOCK },
  ])],
  [ACT.LOOK, syntaxTable("LOOK", [
    { objects: 1, action: V.CHASTISE },
    { objects: 1, prep1: PR.OVER, action: V.LOOK_OVER },
    { objects: 1, prep1: PR.FOR, action: V.FIND },
    { objects: 1, prep1: PR.TO, action: V.EXAMINE },
    { objects: 1, prep1: PR.ON, action: V.EXAMINE },
    { objects: 1, prep1: PR.IN, loc1: SH | SC | SOG | SIR, action: V.LOOK_INSIDE },
    { objects: 1, prep1: PR.BEHIND, action: V.LOOK_BEHIND },
    { objects: 1, prep1: PR.UNDER, action: V.LOOK_UNDER },
    { objects: 1, prep1: PR.OUT, action: V.LOOK_INSIDE },
    { objects: 1, prep1: PR.THROUGH, action: V.LOOK_INSIDE },
    { objects: 1, prep1: PR.AT, loc1: SH | SC | SOG | SIR, action: V.EXAMINE },
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.LOOK_UP },
    { objects: 1, prep1: PR.DOWN, find1: RLANDBIT, action: V.LOOK_DOWN },
    { objects: 1, prep1: PR.AROUND, find1: RLANDBIT, action: V.LOOK },
    { objects: 0, action: V.LOOK },
  ])],
  [ACT.LOVE, syntaxTable("LOVE", [
    { objects: 1, find1: ACTORBIT, action: V.LOVE },
  ])],
  [ACT.LOWER, syntaxTable("LOWER", [
    { objects: 2, prep2: PR.OUT, action: V.PUT_THROUGH },
    { objects: 2, prep2: PR.THROUGH, action: V.PUT_THROUGH },
    { objects: 1, action: V.LOWER },
  ])],
  [ACT.MAKE, syntaxTable("MAKE", [
    { objects: 2, prep2: PR.TO, find2: ACTORBIT, action: V.MAKE_LOVE },
    { objects: 1, prep1: PR.HAPPY, action: V.CHEER },
    { objects: 2, prep2: PR.WITH, action: V.MAKE_WITH },
    { objects: 1, prep1: PR.OUT, find1: RLANDBIT, action: V.MAKE_OUT },
    { objects: 1, action: V.MAKE },
  ])],
  [ACT.MARRY, syntaxTable("MARRY", [
    { objects: 1, find1: ACTORBIT, action: V.MARRY },
  ])],
  [ACT.MASTURBATE, syntaxTable("MASTURBATE", [
    { objects: 0, action: V.MASTURBATE },
  ])],
  [ACT.MEASURE, syntaxTable("MEASURE", [
    { objects: 1, action: V.MEASURE },
  ])],
  [ACT.MOAN, syntaxTable("MOAN", [
    { objects: 0, action: V.MOAN },
  ])],
  [ACT.MOVE, syntaxTable("MOVE", [
    { objects: 2, prep2: PR.TO, action: V.MOVE },
    { objects: 1, prep1: PR.IN, action: V.MOVE },
    { objects: 1, prep1: PR.UP, loc1: SOG | SIR, action: V.RAISE },
    { objects: 1, prep1: PR.AROUND, find1: RLANDBIT, action: V.WALK_AROUND },
    { objects: 2, action: V.PUSH_DIR },
    { objects: 1, prep1: PR.APART, action: V.BEND },
    { objects: 1, loc1: SOG | SIR, action: V.MOVE },
  ])],
  [ACT.NO, syntaxTable("NO", [
    { objects: 0, action: V.NO },
  ])],
  [ACT.OPEN, syntaxTable("OPEN", [
    { objects: 2, prep2: PR.WITH, find1: DOORBIT, loc1: SH | SC | SOG | SIR, loc2: SOG | SIR | SH | SC | SHAVE, action: V.OPEN },
    { objects: 1, prep1: PR.UP, find1: DOORBIT, loc1: SH | SC | SOG | SIR, action: V.OPEN },
    { objects: 1, find1: DOORBIT, loc1: SH | SC | SOG | SIR, action: V.OPEN },
  ])],
  [ACT.PASS, syntaxTable("PASS", [
    { objects: 2, prep2: PR.TO, find2: ACTORBIT, loc1: SMANY | SH | SHAVE, loc2: SOG, action: V.GIVE },
    { objects: 1, action: V.PASS },
  ])],
  [ACT.PAY, syntaxTable("PAY", [
    { objects: 2, prep2: PR.TO, find2: ACTORBIT, loc1: SMANY | SH | SHAVE, loc2: SOG, action: V.GIVE },
    { objects: 1, prep1: PR.FOR, action: V.BUY },
    { objects: 1, find1: ACTORBIT, action: V.PAY },
  ])],
  [ACT.PEE, syntaxTable("PEE", [
    { objects: 1, prep1: PR.ON, action: V.PEE_IN },
    { objects: 1, prep1: PR.IN, action: V.PEE_IN },
    { objects: 0, action: V.PEE },
  ])],
  [ACT.PHONE, syntaxTable("PHONE", [
    { objects: 1, action: V.PHONE },
  ])],
  [ACT.PICK, syntaxTable("PICK", [
    { objects: 1, prep1: PR.UP, find1: TAKEBIT, loc1: SOG | SMANY, action: V.PICK_UP },
    { objects: 2, prep2: PR.WITH, action: V.PICK },
    { objects: 1, action: V.PICK },
  ])],
  [ACT.PIN, syntaxTable("PIN", [
    { objects: 2, prep2: PR.TO, action: V.PIN },
    { objects: 1, action: V.PIN },
  ])],
  [ACT.PLAY, syntaxTable("PLAY", [
    { objects: 1, prep1: PR.WITH, action: V.TOUCH },
  ])],
  [ACT.POINT, syntaxTable("POINT", [
    { objects: 2, prep2: PR.IN, action: V.POINT },
    { objects: 2, prep2: PR.ON, action: V.POINT },
    { objects: 2, prep2: PR.AT, action: V.POINT },
    { objects: 1, prep1: PR.TO, action: V.POINT },
    { objects: 1, prep1: PR.AT, action: V.POINT },
  ])],
  [ACT.POUR, syntaxTable("POUR", [
    { objects: 2, prep2: PR.OUT, loc1: SH | SC, action: V.POUR },
    { objects: 2, prep2: PR.FROM, loc1: SH | SC, action: V.POUR },
    { objects: 2, prep1: PR.OUT, prep2: PR.IN, loc1: SH | SC, action: V.POUR },
    { objects: 2, prep2: PR.IN, loc1: SH | SC, action: V.POUR },
    { objects: 2, prep2: PR.ON, loc1: SH | SC, action: V.POUR },
  ])],
  [ACT.PUSH, syntaxTable("PUSH", [
    { objects: 2, prep2: PR.TO, action: V.PUSH },
    { objects: 2, prep2: PR.IN, action: V.PUSH },
    { objects: 2, prep2: PR.UNDER, action: V.PUT_UNDER },
    { objects: 1, prep1: PR.OFF, find1: RLANDBIT, action: V.PUSH_OFF },
    { objects: 1, prep1: PR.ON, loc1: SIR | SOG, action: V.PUSH },
    { objects: 1, prep1: PR.UP, action: V.RAISE },
    { objects: 2, action: V.PUSH_DIR },
    { objects: 1, action: V.PUSH },
  ])],
  [ACT.RAISE, syntaxTable("RAISE", [
    { objects: 1, prep1: PR.UP, action: V.RAISE },
    { objects: 1, action: V.RAISE },
  ])],
  [ACT.RAKE, syntaxTable("RAKE", [
    { objects: 2, prep2: PR.IN, action: V.PUT },
    { objects: 2, prep2: PR.WITH, loc2: SHAVE, action: V.RAKE },
    { objects: 1, action: V.RAKE },
  ])],
  [ACT.RAPE, syntaxTable("RAPE", [
    { objects: 1, find1: ACTORBIT, action: V.RAPE },
  ])],
  [ACT.REACH, syntaxTable("REACH", [
    { objects: 1, prep1: PR.IN, loc1: SOG | SIR, action: V.REACH_IN },
  ])],
  [ACT.READ, syntaxTable("READ", [
    { objects: 2, prep2: PR.WITH, find1: READBIT, loc1: STAKE, action: V.READ },
    { objects: 2, prep2: PR.THROUGH, find1: READBIT, loc1: STAKE, action: V.READ },
    { objects: 1, prep1: PR.THROUGH, find1: READBIT, loc1: STAKE, action: V.READ },
    { objects: 1, find1: READBIT, loc1: STAKE, action: V.READ },
  ])],
  [ACT.RELIEVE, syntaxTable("RELIEVE", [
    { objects: 1, action: V.RELIEVE },
  ])],
  [ACT.REMOVE, syntaxTable("REMOVE", [
    { objects: 2, prep2: PR.FROM, find1: TAKEBIT, loc1: SIR | SC | SMANY, action: V.TAKE },
    { objects: 1, find1: WORNBIT, action: V.REMOVE },
  ])],
  [ACT.RETURN, syntaxTable("RETURN", [
    { objects: 2, prep2: PR.TO, loc1: SH | SC | SHAVE, loc2: SOG, action: V.RETURN },
    { objects: 1, loc1: SH | SC | SHAVE, action: V.RETURN },
  ])],
  [ACT.RIP, syntaxTable("RIP", [
    { objects: 2, prep2: PR.WITH, action: V.RIP },
    { objects: 1, prep1: PR.UP, action: V.RIP },
    { objects: 2, prep2: PR.IN, action: V.RIP },
    { objects: 1, action: V.RIP },
  ])],
  [ACT.ROLL, syntaxTable("ROLL", [
    { objects: 2, prep2: PR.OVER, action: V.PUT_ON },
    { objects: 2, prep2: PR.ON, action: V.PUT_ON },
    { objects: 1, prep1: PR.UP, action: V.ROLL },
    { objects: 1, action: V.ROLL },
  ])],
  [ACT.RUB, syntaxTable("RUB", [
    { objects: 2, prep2: PR.WITH, action: V.SRUB },
    { objects: 2, prep2: PR.ON, action: V.RUB },
    { objects: 1, action: V.TOUCH },
  ])],
  [ACT.SAY, syntaxTable("SAY", [
    { objects: 1, action: V.USE_QUOTES },
    { objects: 0, action: V.SAY },
  ])],
  [ACT.SCAT, syntaxTable("SCAT", [
    { objects: 0, action: V.SCAT },
  ])],
  [ACT.SCORE, syntaxTable("SCORE", [
    { objects: 1, prep1: PR.WITH, action: V.SCORE },
    { objects: 0, action: V.SCORE },
  ])],
  [ACT.SEARCH, syntaxTable("SEARCH", [
    { objects: 1, prep1: PR.THROUGH, action: V.SEARCH },
    { objects: 1, prep1: PR.FOR, action: V.FIND },
    { objects: 1, prep1: PR.IN, action: V.SEARCH },
    { objects: 1, action: V.SEARCH },
  ])],
  [ACT.SHAKE, syntaxTable("SHAKE", [
    { objects: 2, prep2: PR.WITH, action: V.SHAKE_WITH },
    { objects: 1, action: V.SHAKE },
  ])],
  [ACT.SHIT, syntaxTable("SHIT", [
    { objects: 0, action: V.SHIT },
  ])],
  [ACT.SHOW, syntaxTable("SHOW", [
    { objects: 2, find1: ACTORBIT, loc2: SH | SMANY, action: V.SSHOW },
    { objects: 2, prep2: PR.TO, find2: ACTORBIT, loc1: SH | SMANY, action: V.SHOW },
  ])],
  [ACT.SIGH, syntaxTable("SIGH", [
    { objects: 0, action: V.SIGH },
  ])],
  [ACT.SINK, syntaxTable("SINK", [
    { objects: 1, action: V.SINK },
  ])],
  [ACT.SIT, syntaxTable("SIT", [
    { objects: 1, prep1: PR.IN, loc1: SOG | SIR, action: V.CLIMB_ON },
    { objects: 1, prep1: PR.DOWN, find1: RLANDBIT, loc1: SOG | SIR, action: V.SIT },
    { objects: 1, prep1: PR.ON, loc1: SOG | SIR, action: V.CLIMB_ON },
  ])],
  [ACT.SKIP, syntaxTable("SKIP", [
    { objects: 0, action: V.SKIP },
  ])],
  [ACT.SLEEP, syntaxTable("SLEEP", [
    { objects: 1, prep1: PR.WITH, find1: ACTORBIT, action: V.FUCK },
    { objects: 1, prep1: PR.ON, loc1: SIR | SOG, action: V.BOARD },
    { objects: 1, prep1: PR.IN, loc1: SIR | SOG, action: V.BOARD },
    { objects: 0, action: V.SLEEP },
  ])],
  [ACT.SLICE, syntaxTable("SLICE", [
    { objects: 2, prep1: PR.THROUGH, prep2: PR.WITH, loc2: SC | SH, action: V.CUT },
    { objects: 2, prep2: PR.WITH, loc2: SC | SH, action: V.CUT },
  ])],
  [ACT.SLIDE, syntaxTable("SLIDE", [
    { objects: 1, prep1: PR.DOWN, find1: RLANDBIT, loc1: SOG | SIR, action: V.CLIMB_DOWN },
  ])],
  [ACT.SMEAR, syntaxTable("SMEAR", [
    { objects: 2, prep2: PR.ON, loc1: SH | SMANY, action: V.PUT_ON },
  ])],
  [ACT.SMELL, syntaxTable("SMELL", [
    { objects: 1, action: V.SMELL },
    { objects: 0, action: V.SMELL },
  ])],
  [ACT.STAIN, syntaxTable("STAIN", [
    { objects: 2, prep2: PR.WITH, action: V.STAIN },
    { objects: 1, action: V.STAIN },
  ])],
  [ACT.STAND, syntaxTable("STAND", [
    { objects: 1, prep1: PR.BEHIND, action: V.HIDE },
    { objects: 1, prep1: PR.IN, action: V.STAND_ON },
    { objects: 1, prep1: PR.ON, action: V.STAND_ON },
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.STAND },
    { objects: 0, action: V.STAND },
  ])],
  [ACT.START, syntaxTable("START", [
    { objects: 1, action: V.ON },
  ])],
  [ACT.STICK, syntaxTable("STICK", [
    { objects: 2, prep2: PR.AGAINST, loc1: SHAVE, action: V.PUT_AGAINST },
    { objects: 2, prep2: PR.TO, action: V.PUT_TO },
    { objects: 2, prep2: PR.AT, loc1: SH | SC, action: V.PUT_NEAR },
    { objects: 2, prep2: PR.BEFORE, loc1: SH | SC, action: V.PUT_NEAR },
    { objects: 1, prep1: PR.OUT, find1: ONBIT, action: V.OFF },
    { objects: 2, prep2: PR.OUT, loc1: SMANY, action: V.PUT_THROUGH },
    { objects: 2, prep2: PR.THROUGH, loc1: SMANY, action: V.PUT_THROUGH },
    { objects: 2, prep2: PR.BEHIND, action: V.PUT_BEHIND },
    { objects: 1, prep1: PR.ON, find1: WEARBIT, loc1: SHAVE, action: V.WEAR },
    { objects: 2, prep2: PR.UNDER, action: V.PUT_UNDER },
    { objects: 1, prep1: PR.DOWN, loc1: SH | SMANY | SHAVE, action: V.DROP },
    { objects: 2, prep2: PR.ACROSS, loc1: SH | SMANY, action: V.PUT_ON },
    { objects: 2, prep2: PR.OVER, loc1: SH | SMANY, action: V.PUT_ON },
    { objects: 2, prep2: PR.AROUND, loc1: SH | SMANY, action: V.PUT_ON },
    { objects: 2, prep2: PR.DOWN, loc1: SH | SMANY, action: V.PUT_ON },
    { objects: 2, prep2: PR.ON, loc1: SH | SMANY, action: V.PUT_ON },
    { objects: 2, prep2: PR.IN, loc1: SH | SMANY, action: V.PUT },
  ])],
  [ACT.STIMULATE, syntaxTable("STIMULATE", [
    { objects: 1, find1: ACTORBIT, action: V.ON },
  ])],
  [ACT.SUCK, syntaxTable("SUCK", [
    { objects: 1, prep1: PR.OFF, action: V.SUCK },
    { objects: 1, action: V.SUCK },
  ])],
  [ACT.SUCKLE, syntaxTable("SUCKLE", [
    { objects: 1, action: V.SUCKLE },
  ])],
  [ACT.SWIM, syntaxTable("SWIM", [
    { objects: 1, prep1: PR.IN, action: V.SWIM },
    { objects: 0, action: V.SWIM },
  ])],
  [ACT.SWING, syntaxTable("SWING", [
    { objects: 2, prep2: PR.AT, find2: ACTORBIT, loc1: SH | SC | SHAVE, action: V.SWING },
    { objects: 1, loc1: SH | SC | SHAVE, action: V.SWING },
  ])],
  [ACT.TAKE, syntaxTable("TAKE", [
    { objects: 1, prep1: PR.DRUNK, find1: RLANDBIT, action: V.GET_DRUNK },
    { objects: 1, prep1: PR.SHIT, find1: RLANDBIT, action: V.TAKE_A_SHIT },
    { objects: 1, prep1: PR.LEAK, find1: RLANDBIT, action: V.TAKE_A_LEAK },
    { objects: 1, prep1: PR.PISS, find1: RLANDBIT, action: V.TAKE_A_LEAK },
    { objects: 1, prep1: PR.DOWN, find1: VEHBIT, loc1: SOG, action: V.DISEMBARK },
    { objects: 1, prep1: PR.OUT, find1: VEHBIT, loc1: SOG, action: V.DISEMBARK },
    { objects: 1, prep1: PR.OFF, find1: RLANDBIT, action: V.TAKE_OFF },
    { objects: 2, prep2: PR.WITH, loc1: SIR | SC | SMANY, loc2: SHAVE, action: V.TAKE_WITH },
    { objects: 2, prep2: PR.ON, loc1: SIR | SC | SMANY, action: V.TAKE },
    { objects: 2, prep2: PR.IN, loc1: SIR | SC | SMANY, action: V.TAKE },
    { objects: 2, prep2: PR.FROM, loc1: SIR | SC | SMANY, action: V.TAKE },
    { objects: 2, prep2: PR.OFF, loc1: SC | SIR | SMANY, action: V.TAKE },
    { objects: 2, prep2: PR.OUT, loc1: SC | SIR | SMANY, action: V.TAKE },
    { objects: 1, prep1: PR.UNDRES, find1: RLANDBIT, action: V.GET_UNDRESSED },
    { objects: 1, prep1: PR.DRESSE, find1: RLANDBIT, action: V.GET_DRESSED },
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.STAND },
    { objects: 1, prep1: PR.ON, find1: VEHBIT, loc1: SOG | SIR, action: V.BOARD },
    { objects: 1, prep1: PR.IN, find1: VEHBIT, loc1: SOG | SIR, action: V.BOARD },
    { objects: 1, find1: TAKEBIT, loc1: SOG | SIR | SMANY, action: V.TAKE },
  ])],
  [ACT.TALK, syntaxTable("TALK", [
    { objects: 1, prep1: PR.TO, find1: ACTORBIT, loc1: SIR, action: V.TELL },
  ])],
  [ACT.TAP, syntaxTable("TAP", [
    { objects: 1, prep1: PR.ON, action: V.KNOCK },
    { objects: 1, action: V.TOUCH },
  ])],
  [ACT.TASTE, syntaxTable("TASTE", [
    { objects: 1, action: V.TASTE },
  ])],
  [ACT.TELL, syntaxTable("TELL", [
    { objects: 2, action: V.STELL },
    { objects: 2, prep2: PR.ABOUT, find1: ACTORBIT, action: V.TELL_ABOUT },
    { objects: 1, find1: ACTORBIT, loc1: SIR, action: V.TELL },
  ])],
  [ACT.THANKS, syntaxTable("THANKS", [
    { objects: 0, action: V.THANK },
    { objects: 1, action: V.THANK },
  ])],
  [ACT.THROW, syntaxTable("THROW", [
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.THROW_UP },
    { objects: 2, prep2: PR.OUT, loc1: SH | SC, action: V.PUT_THROUGH },
    { objects: 2, prep2: PR.THROUGH, loc1: SH | SC, loc2: SOG | SIR, action: V.PUT_THROUGH },
    { objects: 2, loc1: SOG | SIR, loc2: SH | SC, action: V.STHROW },
    { objects: 2, prep2: PR.TO, loc1: SH | SC, loc2: SOG | SIR, action: V.THROW_TO },
    { objects: 2, prep2: PR.AT, loc1: SH | SC, loc2: SOG | SIR, action: V.THROW },
    { objects: 2, prep2: PR.DOWN, loc1: SH | SC, action: V.THROW },
    { objects: 2, prep2: PR.IN, loc1: SH | SC, action: V.PUT },
    { objects: 1, prep1: PR.AWAY, loc1: SH | SC, action: V.THROW },
    { objects: 1, loc1: SH | SC, action: V.THROW },
  ])],
  [ACT.TIE, syntaxTable("TIE", [
    { objects: 1, prep1: PR.TOGETHER, action: V.TIE_TOGETHER },
    { objects: 2, prep2: PR.IN, action: V.TIE_TOGETHER },
    { objects: 2, prep2: PR.AROUND, loc1: SH, action: V.TIE },
    { objects: 2, prep2: PR.TO, loc1: SH, action: V.TIE },
  ])],
  [ACT.TOUCH, syntaxTable("TOUCH", [
    { objects: 2, prep2: PR.ON, action: V.TOUCH },
    { objects: 2, prep2: PR.WITH, action: V.TOUCH },
    { objects: 1, action: V.TOUCH },
  ])],
  [ACT.TURN, syntaxTable("TURN", [
    { objects: 1, prep1: PR.OFF, find1: LIGHTBIT, action: V.OFF },
    { objects: 1, prep1: PR.ON, find1: LIGHTBIT, action: V.ON },
    { objects: 2, action: V.SET },
    { objects: 2, prep2: PR.TO, action: V.SET },
    { objects: 1, prep1: PR.AROUND, find1: RLANDBIT, action: V.SET },
    { objects: 1, action: V.SET },
  ])],
  [ACT.UNCOVER, syntaxTable("UNCOVER", [
    { objects: 1, action: V.UNCOVER },
  ])],
  [ACT.UNDRES, syntaxTable("UNDRES", [
    { objects: 1, action: V.UNDRESS },
    { objects: 0, action: V.UNDRESS },
  ])],
  [ACT.UNLOCK, syntaxTable("UNLOCK", [
    { objects: 2, prep2: PR.WITH, loc2: SHAVE, action: V.UNLOCK },
    { objects: 1, action: V.UNLOCK },
  ])],
  [ACT.UNROLL, syntaxTable("UNROLL", [
    { objects: 1, action: V.UNROLL },
  ])],
  [ACT.UNTIE, syntaxTable("UNTIE", [
    { objects: 1, loc1: SOG | SIR | SH | SC, action: V.UNTIE },
  ])],
  [ACT.USE, syntaxTable("USE", [
    { objects: 1, action: V.USE },
  ])],
  [ACT.VOMIT, syntaxTable("VOMIT", [
    { objects: 0, action: V.VOMIT },
  ])],
  [ACT.WAIT, syntaxTable("WAIT", [
    { objects: 1, prep1: PR.FOR, action: V.WAIT_FOR },
    { objects: 0, action: V.WAIT },
  ])],
  [ACT.WAKE, syntaxTable("WAKE", [
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.ALARM },
    { objects: 1, find1: RLANDBIT, action: V.ALARM },
  ])],
  [ACT.WALK, syntaxTable("WALK", [
    { objects: 1, prep1: PR.AWAY, find1: RLANDBIT, action: V.LEAVE },
    { objects: 1, prep1: PR.TO, action: V.WALK_TO },
    { objects: 1, prep1: PR.DOWN, loc1: SOG | SIR, action: V.CLIMB_DOWN },
    { objects: 1, prep1: PR.UP, loc1: SOG | SIR, action: V.CLIMB_UP },
    { objects: 1, prep1: PR.BEHIND, action: V.HIDE },
    { objects: 1, prep1: PR.UNDER, action: V.CRAWL_UNDER },
    { objects: 1, prep1: PR.AROUND, find1: RLANDBIT, action: V.WALK_AROUND },
    { objects: 1, prep1: PR.THROUGH, action: V.ENTER },
    { objects: 1, prep1: PR.OVER, action: V.ENTER },
    { objects: 1, prep1: PR.ON, action: V.STAND_ON },
    { objects: 1, prep1: PR.ACROSS, action: V.ENTER },
    { objects: 1, prep1: PR.OUT, action: V.ENTER },
    { objects: 1, prep1: PR.IN, action: V.ENTER },
    { objects: 1, action: V.WALK },
    { objects: 0, action: V.WALK_AROUND },
  ])],
  [ACT.WASH, syntaxTable("WASH", [
    { objects: 1, prep1: PR.OFF, action: V.CLEAN },
    { objects: 1, prep1: PR.UP, find1: RLANDBIT, action: V.CLEAN },
    { objects: 1, action: V.CLEAN },
  ])],
  [ACT.WEAR, syntaxTable("WEAR", [
    { objects: 1, find1: WEARBIT, loc1: SHAVE, action: V.WEAR },
  ])],
  [ACT.WHAT, syntaxTable("WHAT", [
    { objects: 1, action: V.WHAT },
  ])],
  [ACT.WHERE, syntaxTable("WHERE", [
    { objects: 1, action: V.WHERE },
  ])],
  [ACT.WHIP, syntaxTable("WHIP", [
    { objects: 2, prep2: PR.WITH, loc2: SHAVE, action: V.WHIP },
    { objects: 1, action: V.WHIP },
  ])],
  [ACT.WRAP, syntaxTable("WRAP", [
    { objects: 2, prep2: PR.IN, loc2: SH | SMANY, action: V.SWRAP },
    { objects: 2, prep2: PR.AROUND, loc1: SH | SMANY, action: V.WRAP },
  ])],
  [ACT.YELL, syntaxTable("YELL", [
    { objects: 1, prep1: PR.TO, action: V.YELL },
    { objects: 1, prep1: PR.AT, action: V.YELL },
    { objects: 0, action: V.YELL },
  ])],
  [ACT.YES, syntaxTable("YES", [
    { objects: 0, action: V.YES },
  ])],
  [ACT.ZZMGCK, syntaxTable("ZZMGCK", [
    { objects: 1, action: V.ANSWER_KLUDGE },
  ])],
]);

/** The routine that carries out each action. */
export const ACTIONS = actionTable("ACTIONS", [
  [V.VERBOSE, vVerbose],
  [V.BRIEF, vBrief],
  [V.SUPER_BRIEF, vSuperBrief],
  [V.TAME, vTame],
  [V.SUGGESTIVE, vSuggestive],
  [V.LEWD, vLewd],
  [V.DIAGNOSE, vDiagnose],
  [V.INVENTORY, vInventory],
  [V.QUIT, vQuit],
  [V.RESTART, vRestart],
  [V.RESTORE, vRestore],
  [V.SAVE, vSave],
  [V.STATUS, vStatus],
  [V.SCRIPT, vScript],
  [V.UNSCRIPT, vUnscript],
  [V.VERSION, vVersion],
  [V.$RANDOM, vDollarRandom],
  [V.$COMMAND, vDollarCommand],
  [V.$RECORD, vDollarRecord],
  [V.$UNRECORD, vDollarUnrecord],
  [V.$VERIFY, vDollarVerify],
  [V.ANSWER, vAnswer],
  [V.USE_QUOTES, vUseQuotes],
  [V.APPLAUD, vApplaud],
  [V.APPLY, vApply],
  [V.PUT_ON, vPutOn],
  [V.WALK_TO, vWalkTo],
  [V.ASK_ABOUT, vAskAbout],
  [V.ASK_FOR, vAskFor],
  [V.ASK_NO_ONE_FOR, vAskNoOneFor],
  [V.KILL, vKill],
  [V.BARTER_WITH, vBarterWith],
  [V.BARTER_FOR, vBarterFor],
  [V.BEND, vBend],
  [V.BITE, vBite],
  [V.BLOW, vBlow],
  [V.INFLATE, vInflate],
  [V.OFF, vOff],
  [V.BOARD, vBoard],
  [V.BOARD_DIR, vBoardDir],
  [V.INHALE, vInhale],
  [V.BURN, vBurn],
  [V.BUY, vBuy],
  [V.BUY_WITH, vBuyWith],
  [V.CALL, vCall],
  [V.CAST_OFF, vCastOff],
  [V.CATCH, vCatch],
  [V.CHEER, vCheer],
  [V.WALK_AROUND, vWalkAround],
  [V.CLICK, vClick],
  [V.CLIMB, vClimb],
  [V.CLIMB_ON, vClimbOn],
  [V.CLIMB_UP, vClimbUp],
  [V.CLIMB_DOWN, vClimbDown],
  [V.DISEMBARK, vDisembark],
  [V.CLIMB_OVER, vClimbOver],
  [V.ENTER, vEnter],
  [V.CRAWL_UNDER, vCrawlUnder],
  [V.CLOSE, vClose],
  [V.SHUT_UP, vShutUp],
  [V.COME, vCome],
  [V.FOLLOW, vFollow],
  [V.COPULATE, vCopulate],
  [V.SPUT_ON, vSputOn],
  [V.COUNT, vCount],
  [V.CROSS, vCross],
  [V.DECODE, vDecode],
  [V.DEFLATE, vDeflate],
  [V.MUNG, vMung],
  [V.DIG, vDig],
  [V.DRESS, vDress],
  [V.DRINK, vDrink],
  [V.DRINK_FROM, vDrinkFrom],
  [V.DROP, vDrop],
  [V.PUT, vPut],
  [V.PUT_THROUGH, vPutThrough],
  [V.PUT_NEAR, vPutNear],
  [V.EAT, vEat],
  [V.EMPTY, vEmpty],
  [V.EMPTY_FROM, vEmptyFrom],
  [V.IN, vIn],
  [V.EXAMINE, vExamine],
  [V.EXIT, vExit],
  [V.FEED, vFeed],
  [V.GIVE, vGive],
  [V.SGIVE, vSgive],
  [V.FILL, vFill],
  [V.FIND, vFind],
  [V.FLUSH, vFlush],
  [V.FUCK, vFuck],
  [V.GIDDYAP, vGiddyap],
  [V.WALK, vWalk],
  [V.HIDE, vHide],
  [V.LEAVE, vLeave],
  [V.GIVE_UP, vGiveUp],
  [V.RETURN, vReturn],
  [V.LISTEN, vListen],
  [V.HELLO, vHello],
  [V.HELP, vHelp],
  [V.SAVE_SOMETHING, vSaveSomething],
  [V.HISS, vHiss],
  [V.MASTURBATE, vMasturbate],
  [V.WHIP, vWhip],
  [V.LEAP, vLeap],
  [V.LEAP_OFF, vLeapOff],
  [V.STAND_ON, vStandOn],
  [V.KICK, vKick],
  [V.KISS, vKiss],
  [V.KISS_ON, vKissOn],
  [V.KNEEL, vKneel],
  [V.KNOCK, vKnock],
  [V.KWEEPA, vKweepa],
  [V.LAND, vLand],
  [V.LAUGH, vLaugh],
  [V.LAUNCH, vLaunch],
  [V.PUT_AGAINST, vPutAgainst],
  [V.LICK, vLick],
  [V.LIE_DOWN, vLieDown],
  [V.ON, vOn],
  [V.LIMBER, vLimber],
  [V.LOCK, vLock],
  [V.LOOK, vLook],
  [V.LOOK_DOWN, vLookDown],
  [V.LOOK_UP, vLookUp],
  [V.LOOK_INSIDE, vLookInside],
  [V.LOOK_UNDER, vLookUnder],
  [V.LOOK_BEHIND, vLookBehind],
  [V.LOOK_OVER, vLookOver],
  [V.CHASTISE, vChastise],
  [V.LOVE, vLove],
  [V.LOWER, vLower],
  [V.MAKE, vMake],
  [V.MAKE_OUT, vMakeOut],
  [V.MAKE_WITH, vMakeWith],
  [V.MAKE_LOVE, vMakeLove],
  [V.MARRY, vMarry],
  [V.MEASURE, vMeasure],
  [V.MOAN, vMoan],
  [V.MOVE, vMove],
  [V.PUSH_DIR, vPushDir],
  [V.RAISE, vRaise],
  [V.NO, vNo],
  [V.OPEN, vOpen],
  [V.PASS, vPass],
  [V.PAY, vPay],
  [V.PEE, vPee],
  [V.PEE_IN, vPeeIn],
  [V.PHONE, vPhone],
  [V.PICK, vPick],
  [V.PICK_UP, vPickUp],
  [V.PIN, vPin],
  [V.TOUCH, vTouch],
  [V.POINT, vPoint],
  [V.POUR, vPour],
  [V.PUSH, vPush],
  [V.PUSH_OFF, vPushOff],
  [V.PUT_UNDER, vPutUnder],
  [V.RAKE, vRake],
  [V.RAPE, vRape],
  [V.REACH_IN, vReachIn],
  [V.READ, vRead],
  [V.RELIEVE, vRelieve],
  [V.REMOVE, vRemove],
  [V.TAKE, vTake],
  [V.RIP, vRip],
  [V.ROLL, vRoll],
  [V.RUB, vRub],
  [V.SRUB, vSrub],
  [V.SAY, vSay],
  [V.SCAT, vScat],
  [V.SCORE, vScore],
  [V.SEARCH, vSearch],
  [V.SHAKE, vShake],
  [V.SHAKE_WITH, vShakeWith],
  [V.SHIT, vShit],
  [V.SHOW, vShow],
  [V.SSHOW, vSshow],
  [V.SIGH, vSigh],
  [V.SINK, vSink],
  [V.SIT, vSit],
  [V.SKIP, vSkip],
  [V.SLEEP, vSleep],
  [V.CUT, vCut],
  [V.SMELL, vSmell],
  [V.STAIN, vStain],
  [V.STAND, vStand],
  [V.WEAR, vWear],
  [V.PUT_BEHIND, vPutBehind],
  [V.PUT_TO, vPutTo],
  [V.SUCK, vSuck],
  [V.SUCKLE, vSuckle],
  [V.SWIM, vSwim],
  [V.SWING, vSwing],
  [V.GET_DRESSED, vGetDressed],
  [V.GET_UNDRESSED, vGetUndressed],
  [V.TAKE_WITH, vTakeWith],
  [V.TAKE_OFF, vTakeOff],
  [V.TAKE_A_LEAK, vTakeALeak],
  [V.TAKE_A_SHIT, vTakeAShit],
  [V.GET_DRUNK, vGetDrunk],
  [V.TELL, vTell],
  [V.TASTE, vTaste],
  [V.TELL_ABOUT, vTellAbout],
  [V.STELL, vStell],
  [V.THANK, vThank],
  [V.THROW, vThrow],
  [V.THROW_TO, vThrowTo],
  [V.STHROW, vSthrow],
  [V.THROW_UP, vThrowUp],
  [V.TIE, vTie],
  [V.TIE_TOGETHER, vTieTogether],
  [V.SET, vSet],
  [V.UNCOVER, vUncover],
  [V.UNDRESS, vUndress],
  [V.UNLOCK, vUnlock],
  [V.UNROLL, vUnroll],
  [V.UNTIE, vUntie],
  [V.USE, vUse],
  [V.VOMIT, vVomit],
  [V.WAIT, vWait],
  [V.WAIT_FOR, vWaitFor],
  [V.ALARM, vAlarm],
  [V.CLEAN, vClean],
  [V.WHAT, vWhat],
  [V.WHERE, vWhere],
  [V.WRAP, vWrap],
  [V.SWRAP, vSwrap],
  [V.YELL, vYell],
  [V.YES, vYes],
  [V.ANSWER_KLUDGE, vAnswerKludge],
]);

/** Routines run before an action's own handlers get a chance. */
export const PREACTIONS = actionTable("PREACTIONS", [
  [V.PUT_ON, prePut],
  [V.ASK_ABOUT, preSpeak],
  [V.ASK_FOR, preSpeak],
  [V.OFF, preTouch],
  [V.BOARD, preBoard],
  [V.BURN, preTouch],
  [V.CLOSE, preTouch],
  [V.DROP, idrop],
  [V.PUT, prePut],
  [V.PUT_THROUGH, idrop],
  [V.PUT_NEAR, idrop],
  [V.EMPTY, preTouch],
  [V.EXAMINE, preLook],
  [V.GIVE, preGive],
  [V.FUCK, preFuck],
  [V.LISTEN, preListen],
  [V.KISS, preTouch],
  [V.ON, preTouch],
  [V.LOOK_DOWN, preLook],
  [V.LOOK_UP, preLook],
  [V.LOOK_INSIDE, preLook],
  [V.LOOK_UNDER, preLook],
  [V.LOOK_BEHIND, preLook],
  [V.LOOK_OVER, preLook],
  [V.MOVE, preTouch],
  [V.RAISE, preTouch],
  [V.OPEN, preTouch],
  [V.PICK_UP, preTake],
  [V.TOUCH, preTouch],
  [V.POUR, prePour],
  [V.RAKE, preRake],
  [V.READ, preLook],
  [V.TAKE, preTake],
  [V.ROLL, preTouch],
  [V.RUB, preTouch],
  [V.SMELL, preSmell],
  [V.TELL, preSpeak],
  [V.TELL_ABOUT, preSpeak],
  [V.THROW, idrop],
  [V.THROW_TO, idrop],
  [V.WRAP, prePut],
]);

/** Canonical word for each preposition number. */
export const PREPOSITIONS = prepositionTable([
  [word("to"), PR.TO],
  [word("about"), PR.ABOUT],
  [word("on"), PR.ON],
  [word("for"), PR.FOR],
  [word("with"), PR.WITH],
  [word("up"), PR.UP],
  [word("out"), PR.OUT],
  [word("hard"), PR.HARD],
  [word("from"), PR.FROM],
  [word("off"), PR.OFF],
  [word("in"), PR.IN],
  [word("down"), PR.DOWN],
  [word("over"), PR.OVER],
  [word("through"), PR.THROUGH],
  [word("under"), PR.UNDER],
  [word("before"), PR.BEFORE],
  [word("at"), PR.AT],
  [word("around"), PR.AROUND],
  [word("behind"), PR.BEHIND],
  [word("away"), PR.AWAY],
  [word("back"), PR.BACK],
  [word("across"), PR.ACROSS],
  [word("against"), PR.AGAINST],
  [word("go"), PR.GO],
  [word("happy"), PR.HAPPY],
  [word("apart"), PR.APART],
  [word("dresse"), PR.DRESSE],
  [word("undres"), PR.UNDRES],
  [word("piss"), PR.PISS],
  [word("leak"), PR.LEAK],
  [word("shit"), PR.SHIT],
  [word("drunk"), PR.DRUNK],
  [word("together"), PR.TOGETHER],
]);
